---
title: Digitally Well
timezone: America/Guatemala
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@getdigitallywell.com
description: Stay on the cutting edge of how technology is shaping our lives and learn
  to stay focused in an increasingly distracted world.
baseurl: 
url: 
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
minima:
  social_links:
    twitter: digitally_well
    facebook: digitallywell
    instagram: digitally_well
google_analytics: UA-140161188-4
show_excerpts: true
disqus:
  shortname: digitally-well
defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/blog/authors/:title/"
    layout: author
    twitter:
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: Madi Thomas
    featured-image:
    featured-image-alt: